nome = str("Gabriel")
sobrenome = str("Soares")
idade = int(22)
ano_nascimento = int(2000)
maior_idade = bool(idade >= 18)
altura_metros = float(1.69)

print("Nome:", nome)
print("Sobrenome:", sobrenome)
print("Idade:", idade)
print("Ano de nascimento:", ano_nascimento)
print("È maior de idade:", maior_idade)
print("Aultura em metros é:",altura_metros)
